apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: INTER_NODE_LINK_TYPE
        value: VXLAN
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: MESHNET_PROPAGATE_CARRIER
        value: "1"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: MESHNET_DATAPATH_IFACE_PREFIX
        value: eno
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: MESHNET_DEFAULT_LINK_MTU
        value: "9300"
  target:
    kind: DaemonSet
    name: meshnet
    namespace: meshnet
resources:
- ../../base/
images:
- name: public.ecr.aws/drivenets/meshnet-cni
  newTag: 2b5d372-dirty
